name: inner_kid
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1

  # Storage & Preferences
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.5.3

  # Utilities
  uuid: ^4.5.1
  get_it: ^8.0.3
  intl: ^0.19.0
  logger: ^2.5.0

  # UI & Animation
  flutter_animate: ^4.2.0
  lottie: ^3.3.1
  google_fonts: ^6.1.0
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.6
  firebase_analytics: ^11.5.0
  google_sign_in: ^6.1.6

  # Additional UI
  figma_squircle: ^0.6.3
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  fl_chart: ^0.71.0
  percent_indicator: ^4.2.1

  # Image processing
  image: ^4.2.0
  path: ^1.8.3

  # Video player
  video_player: ^2.8.3

  # Environment variables
  flutter_dotenv: ^5.1.0

  # HTTP client
  http: ^1.2.2
  purchases_flutter: ^9.1.0

  icons_launcher: ^3.0.1

  # Device Preview
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/elements/
    - assets/lotties/
    - assets/video/
    - assets/brand/
    - .env
# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/icons/app_icon.flutpg"
#   adaptive_icon_background: "#FFFFFF" # Choose an appropriate background color
#   adaptive_icon_foreground: "assets/icons/islami_app_icon.jpg"
#   min_sdk_android: 21 # Android sdk min version

icons_launcher:
  image_path: "assets/brand/innerkid_logo_1.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
